version: "2"
linters:
  default: none
  enable:
    - govet
    - ineffassign
    - misspell
  disable:
    - staticcheck
  settings:
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - wrapperFunc
      enabled-tags:
        - performance
        - style
        - experimental
    gocyclo:
      min-complexity: 10
    lll:
      line-length: 140
    misspell:
      locale: US
      ignore-rules:
        - nto
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        text: weak cryptographic primitive
      - linters:
          - staticcheck
        text: "S1009:"
      - linters:
          - staticcheck
        text: "S1034:"
      - linters:
          - staticcheck
        text: "SA1019:"
      - linters:
          - staticcheck
        text: "ST1001:"
      - linters:
          - staticcheck
        text: "ST1017:"
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  settings:
    goimports:
      local-prefixes:
        - github.com/golangci/golangci-lint
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
